pnu-code-place/code-place

fixtures/college.json, fixtures/department_1.json, fixtures/department_10.json, fixtures/department_11.json, fixtures/department_12.json, fixtures/department_13.json, fixtures/department_14.json, fixtures/department_15.json, fixtures/department_2.json, fixtures/department_3.json, fixtures/department_4.json, fixtures/department_5.json, fixtures/department_6.json, fixtures/department_7.json, fixtures/department_8.json, fixtures/department_9.json, init_db.sh
회원가입 및 서비스에 필요한 단과대학과 학과정보 fixture를 추가하였습니다.
=> #15/회원가입 fixtures 추가

problem/utils.py
- 문제가 하나도 없을 시 예외처리 추가
- 영역 중복을 최대한 허용하되, 3문제를 보너스문제로 설정하는 것을 가장 최우선으로 보장하도록 로직 변경. 따라서 3문제를 추천할 수 없다면 영역 중복을 허용하여 보너스문제로 설정
- 지난 주 보너스문제를 이번 주 보너스문제로 설정하지 않도록 로직 변경
- 로컬에 임의로 문제를 등록하여 테스트 🅾️
N/A
N/A
N/A
=> 보너스문제 설정 Scheduler Job 예외처리 추가, 3문제를 추천하는 것을 최우선으로 로직 수정

backend/docker-compose.yml, scheduler/Dockerfile, scheduler/announcement/tasks.py, scheduler/deploy/exec_gunicorn.sh, scheduler/deploy/requirements.txt, scheduler/utils/scheduler.py
- scheduler app의 Dockerfile을 작성하였습니다.
- 이를 Docker compose.yml 파일에 정의하였습니다.
=> #120 deploy scheduler app 배포 구성

backend/announcement/tests.py, backend/announcement/views/oj.py, backend/contents/serializers.py, backend/contents/tests.py, backend/contents/urls/oj.py, backend/contents/views/oj.py, backend/problem/tests.py
주요 변경사항
---
- 홈에서 사용하는 공지사항용 API를 분리하여 따로 구현하였습니다.
- 공지사항 페이지 내부에서 사용하는 기존 API에 QueryParam(id)을 추가하여, 개별 공지사항 데이터를 조회할 수 있도록 변경하였습니다.
=> 공지사항 API 개선

backend/.gitignore, backend/deploy/entrypoint.sh, backend/deploy/nginx/nginx.conf, backend/deploy/nginx/ssl_config.conf, backend/docker-compose.yml, backend/problem/tests.py
- 새로운 도메인 주소에 따른 설정 변경
- 운영환경 컨테이너 내부에서 배너 관련 디렉토리를 자동생성하도록 변경
=> #172 deploy 도메인 주소 변경에 따른 배포 설정 변경

frontend/src/pages/admin/views/problem/AddPublicProblem.vue, frontend/src/pages/oj/router/routes.js, frontend/src/pages/oj/views/home/HomeProfileBox.vue, frontend/src/pages/oj/views/home/Notice/HomeNoticeItem.vue, frontend/src/pages/oj/views/problem/problemList/problemListComponent/ProblemListTable.vue, frontend/src/pages/oj/views/rank/UserRank.vue, frontend/src/pages/oj/views/setting/UserSetting.vue, frontend/src/pages/oj/views/user/Register.vue, frontend/src/pages/oj/views/user/userhome/UserCard.vue, frontend/src/pages/oj/views/user/userhome/sections/dashboardSection/FieldSummary.vue, frontend/src/utils/constants.js
7b0e5f6f0ef9a8ec1ff2e312bfaf3ef9a32f1fbb
468acef6d889f01d744f67f343f011331be8e0dd
0a70a6d6aecb55fcc5d7b923d734787f1e33143c
위의 셋 커밋 이후에 새로고침하지 않을 경우 새로고침해야 코드의 변경사항이 적용되는 현상이 개발환경에서 발견됨, 이 현상이 지속될 경우 롤백 필요
=> 171 대회와 문제풀이 qa

frontend/src/pages/oj/components/LogoButton.vue, frontend/src/pages/oj/components/NavBar.vue
- 메인 Navbar의 padding을 삭제하고, 메인 Navbar의 내부 요소들(로고 박스, 프로필 드롭다운)에 margin 값을 적용하여 해결하였습니다.
=> #179 [FE] 메인 navbar elevation 문제 해결

backend/contest/views/oj.py, frontend/src/pages/oj/views/contest/ContestHistory.vue
- Django Object(Contest)에 날짜를 계산하는 필터가 누락된 부분을 확인하여 수정하였습니다.
=> #181 최근에 마감된 대회에 진행 중인 대회가 뜨는 오류

backend/account/views/oj.py, backend/judge/dispatcher.py
- 예전 개발 환경코드가 파이썬 인덴트 문제로 운영환경에 영향을 미치고 있어, 해당 개발 환경용 코드를 삭제하였습니다.
=> Oi 대회에서 부분 점수가 전체점수로 반영되는 오류 해결

frontend/src/i18n/oj/en-US.js, frontend/src/pages/oj/components/CustomTooltip.vue, frontend/src/pages/oj/views/contest/children/ACMContestRank.vue, frontend/src/pages/oj/views/contest/children/ContestProblemList.vue, frontend/src/pages/oj/views/contest/children/OIContestRank.vue
=> #234 대회의 랭킹 페이지 디자인 수정 및 기능 추가

frontend/Dockerfile, frontend/deploy/entrypoint.sh, frontend/deploy/nginx/nginx.conf, frontend/deploy/nginx/ssl_config.conf
- 도커파일의 전역 빌드 인수(server_name)를 프로덕션 스테이지로 넘기고, entrypoint.sh에서 sed를 이용해 동적 변경하도록 수정
=> #246 fe 프론트엔드 이미지 빌드 시 server name 주입

frontend/src/pages/oj/views/problem/problemSolving/Problem.vue, frontend/src/pages/oj/views/problem/problemSolving/problemSolvingComponent/CodeEditor.vue, frontend/src/pages/oj/views/problem/problemSolving/problemSolvingComponent/CodeEditorHeader.vue, frontend/src/pages/oj/views/problem/problemSolving/problemSolvingComponent/ProblemDetailFlexibleContainer.vue, frontend/src/styles/github-light.css
* fix: 사용하지 않는 코드 제거
* fix: 코드에디터 폰트 사이즈 변경
* feat: 코드에디터에 브라켓 매칭 후 하이라이팅 기능 추가
* feat: 코드에디터에 활성 라인 표기 기능 추가
* feat: 인덴트 사이즈 변경
* feat :여러 라인을 동시에 탭할때 인덴트 하는 기능 추가
* feat: 브라켓 매칭 하이라이팅 디자인 추가
* fix: 사용하지 않는 코드 제거
* fix: 이외 warning 수정
=> Release 1.1.0

frontend/src/i18n/oj/en-US.js, frontend/src/pages/oj/api.js, frontend/src/pages/oj/views/contest/children/ContestProblemList.vue, frontend/src/store/modules/contest.js
=> #275 대회 문제 목록 페이지에 기능 추가

frontend/src/i18n/oj/en-US.js, frontend/src/pages/oj/views/contest/children/ContestProblemList.vue
=> #295 대회 문제 페이지에서 제출현황에 툴팁 추가

frontend/src/pages/oj/views/contest/children/ContestProblemList.vue
=> FE 대회 문제 목록에서 페이지네이션 삭제

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/docs_bug.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/improvement_request.md, .github/ISSUE_TEMPLATE/question_support.md
- `Enhancement Request` -> `Improvement Request` 로 변경
- 제목에 이중 띄어쓰기 제거
N/A
N/A
N/A
=> # 317 Issue Template 개선

hub/scripts/authorize.js, hub/scripts/background.js
- 사용자가 OAuth2 인증을 하면 발급되는 임시토큰을 이용해 실제 토큰을 가져오는 스크립트 추가
- OAuth 인증 이후 토큰이 Local Storage에 잘 저장되는지 확인 (제 계정을 지키기 위해 일부만 캡처했습니다 ㅎ)
N/A
N/A
=> #327 GitHub 토큰 발급 및 저장 스크립트 작성

hub/scripts/github.js
- Branch의 Head 업데이트, Reference 가져오기 등 GitHub 유틸리티 함수 추가 (from LeetHub)
N/A
N/A
N/A
=> #335 GitHub 유틸리티 함수 추가

hub/scripts/enable.js, hub/scripts/storage.js, hub/scripts/util.js
- `enable.js`, `storage.js`, `util.js` 추가
N/A
N/A
N/A
=> #337 Code Place Hub 유틸리티 함수 추가

hub/scripts/code-place/parse.js, hub/scripts/code-place/upload.js, hub/scripts/code-place/variables.js
-기존에 존재하던 레포지토리를 연결하는 경우나 Code Place 이외의 다른 코드가 존재하는 경우에 Code Place를 분리하기 위해 `SOLUTIONS_DIRECTORY` 생성
- Code Place에서 해결하고 자동으로 커밋된 문제들은 모두 `/code_place/` 아래에 저장됨
- 제출된 코드 이름 `solution.{확장자}`로 고정
- 로컬에서 문제 해결 후 잘 커밋되는지 확인
N/A
N/A
=> #347 Code Place Hub 레포지토리 파일 구조 개선

hub/scripts/background.js, hub/scripts/code-place/code_place.js, hub/scripts/code-place/variables.js
- Background Worker에서 URL을 관찰하고 문제 해결 페이지인 경우에 `code_place.js`로 chrome message 전송
- `code_place.js`는 제출 버튼이 클릭된 경우에만 Submit 상태 관찰
- 로컬에서 제출 > 업로드 확인
N/A
N/A
=> #350 Code Place Hub 문제 풀이 페이지인 경우만 Submit 상태 관찰

hub/scripts/code-place/code_place.js
- 네트워크 에러나 모종의 이유로 인해 제출 상태가 업데이트 되지 않으면 TimeOut (Loader 중지)
- 고의적으로 제출 상태가 업데이트 되지 않도록 만든 후 TimeOut이 정상적으로 되는지 확인
N/A
N/A
=> #350 Code Place Hub 일정 시간동안 제출 상태가 업데이트 되지 않으면 TimeOut

hub/library/sha1.min.js, hub/scripts/code-place/code_place.js
- SHA1 Library 추가
- 이미 제출된 코드와 새로운 코드의 SHA값을 비교하여 중복된 경우 Skip
N/A
N/A
=> Code Place Hub 중복된 코드가 이미 업로드 된 경우 다음 업로드 Skip

hub/auth_server/Dockerfile, hub/auth_server/requirements.txt
- Code Place Hub 인증 서버 Dockerfile 생성
- `uvicorn`으로 ASGI 실행
- Docker Image 빌드
- Docker Container 작동
N/A
N/A
=> #353 Code Place Hub 인증 서버 Dockerfile 생성

hub/manifest.json
- `code.pusan.ac.kr`에 접속한 경우 Code Place Hub가 동작할 수 있도록 `manifest.json`의 `content_scripts`에 `code.pusan.ac.kr` 추가
로컬 테스트
N/A
N/A
=> #350 Code Place Hub content_scripts 추가

.github/workflows/ci2develop.yml, .github/workflows/ci2production-and-release.yml
- CI 파이프라인에 `hub-auth` 파이프라인 추가
- `hub/auth_server/`에 변경사항이 있으면 registry에 새로운 이미지 푸시
- Dummy Commit을 생성하여 `ci-hub-auth`가 정상적으로 작동하는지 확인
**- 이제 Release에 Code Place Hub 인증 서버도 같이 릴리즈됩니다.**
N/A
=> #367 Code Place Hub 인증 서버 CI 파이프라인 구축

hub/manifest.json, hub/scripts/code-place/code_place.js, hub/scripts/code-place/toast_message.js
- 사용자가 Hub의 업로드 상태를 확인하기 쉽도록 Toast Message를 추가하였습니다.
- 다음 3가지의 경우에 Toast Message를 출력합니다.
- 업로드 시작
- 업로드 완료
- 이미 제출된 코드인 경우
N/A
N/A
=> #353 Code Place Hub 토스트 메시지 구현

hub/scripts/authorize.js, hub/scripts/oauth2.js
- OJ서버에 인증 서버 세팅이 완료되었으므로 URL을 인증 서버로 수정합니다.
N/A
N/A
N/A
=> #353 Code Place Hub가 인증 서버를 사용하도록 구현

hub/_locales/en/messages.json, hub/_locales/ko/messages.json, hub/assets/code-place-logo.svg, hub/css/popup.css, hub/manifest.json, hub/popup.html, hub/popup.js
- Code Place Hub의 Popup 페이지의 UI를 개선하였습니다. (Chrome Extension에서 Code Place Hub를 클릭하면 뜨는 페이지)
- `i18n`을 추가하여 다국어를 지원하도록 변경하였습니다.
- 한국어, English 지원
- Authenticate 이전 Popup 화면
- Authenticate 이후 Popup 화면
N/A
N/A
=> #373 Code Place Hub UI 개선 및 리팩토링

hub/_locales/en/messages.json, hub/_locales/ko/messages.json, hub/css/popup.css, hub/css/welcome.css, hub/popup.html, hub/welcome.html, hub/welcome.js
- Welcome Page의 페이지의 UI를 개선하였습니다. (Popup 페이지와 유사한 레이아웃으로 구성)
- `welcome.js` 코드 전체 리팩토링하였습니다.
- 기능별로 묶어 가독성을 개선하였습니다.
- `UI`: `i18n`을 통한 언어별 텍스트 변경, Element에 EventListener추가, 특정 Element 보여주거나 숨기기
- `RepoManager`: Option별 GitHub API 요청 및 로컬 스토리지에 토큰 저장
- `GitHubAPI`: Github Repository 생성하거나 연결
- `StorageManager`: 로컬 스토리지 관리
N/A
N/A
=> #373 Code Place Hub Welcome 페이지 UI 수정

hub/_locales/en/messages.json, hub/_locales/ko/messages.json, hub/scripts/code-place/code_place.js, hub/scripts/enable.js, hub/welcome.js
- 아래의 정보를 토스트 메시지로 나타내도록 개선하였습니다.
- 업로드 준비 완료 되었는지
- Extension 활성화 여부
- 세팅이 완료되지 않아 업로드를 할 수 없는 경우
- 업로드 준비 완료
- 불완전한 세팅
- Extension 비활성화
N/.A
N/A
=> #380 Code Place Hub 토스트 메시지 구체화

hub/_locales/en/messages.json, hub/_locales/ko/messages.json, hub/css/welcome.css, hub/welcome.html, hub/welcome.js
- 아래의 element에 대해 `i18n`을 통하여 다국어 지원 구체화
- 에러 메시지
- 레포지토리 링크 옵션 선택
- 에러 메시지
- 레포지토리 링크 옵션 선택
N/A
N/A
=> #373 Code Place Hub 다국어 지원 구체화

hub/_locales/en/messages.json, hub/_locales/ko/messages.json, hub/css/popup.css, hub/popup.html, hub/popup.js
- 팝업 페이지에서 초기화 버튼을 클릭하면 local storage를 초기화하고 새로운 계정 및 레포지토리를 연동할 수 있도록 구현하였습니다.
- Footer의 오른쪽에 초기화 버튼을 추가하여 UI를 디자인하였습니다.
- 레포지토리 연동 이후 팝업 창
- 초기화 버튼 클릭 후 다른 레포지토리 연결 테스트
N/A
N/A
=> #383 Code Place Hub 초기화 버튼 추가

backend/profile/views/oj.py, frontend/src/i18n/oj/en-US.js, frontend/src/pages/oj/views/user/userhome/sections/problemSection/ProblemSectionList.vue
- 마이페이지 > 문제 풀이 탭에 날짜 필터 컴포넌트를 추가하였습니다.
- `ProfileProblemAPIView`에서 Submission을 날짜 기준으로 필터링 할 수 있도록 변경하였습니다.
- `ProfileProblemAPIView`에 DocString을 추가하였습니다.
- 날짜 선택 화면
- 필터링 결과
- 검증
N/A
N/A
=> #357 마이페이지 문제 풀이 탭에 날짜 필터링 추가

backend/profile/views/oj.py, frontend/src/i18n/oj/en-US.js, frontend/src/pages/oj/views/contest/children/ContestProblemList.vue, frontend/src/pages/oj/views/user/Register.vue, frontend/src/pages/oj/views/user/userhome/sections/problemSection/ProblemSectionList.vue, hub/_locales/en/messages.json, hub/_locales/ko/messages.json, hub/css/popup.css, hub/css/welcome.css, hub/manifest.json, hub/popup.html, hub/popup.js, hub/scripts/background.js, hub/scripts/code-place/code_place.js, hub/scripts/enable.js, hub/welcome.html, hub/welcome.js
- Code Place Hub 개선 작업 & 배포
- 회원가입 창에 부산대학교 웹메일 관련 안내 추가
- 대회 문제 탭에서 전체 문제 개수 표시
- 마이페이지 문제 풀이 탭에서 날짜 필터링 추가
=> Release 1.3.4

.gitignore, backend/backup.sh, deployment/.env.example
- `pg_dump`를 이용하여 Postgres 데이터베이스를 백업한 후, S3에 업로드합니다.
- `data/assets/`, `/data/backend/`, `/data/config/` 를 압축하여 S3에 업로드합니다.
- `deployment/` 디렉토리에 있는 .env 파일의 예시를 추가하였습니다.
- `.env`는 모든 디렉토리에 대해 git ignore 설정하였습니다.
- Dev 환경에서 백업 스크립트 실행 결과
- S3 버켓에 데이터 확인
- 이제 데이터베이스를 주기적으로 백업할 수 있습니다. 데이터가 유실된 경우, S3 버킷에서 최신 백업을 다운로드하여 복구합니다.
N/A
=> #402 데이터베이스 및 중요 데이터 S3 백업

.github/workflows/ci2production-and-release.yml
=> #NOISSUE CI Workflow Syntax Error 해결

.github/workflows/ci2production-and-release.yml
Github Workflow Syntax Error 해결
=> #NOISSUE CI Workflow Syntax Error 해결 (#408)

.github/workflows/ci2production-and-release.yml
Reverts pnu-code-place/code-place#409
=> Revert "#NOISSUE CI Workflow Syntax Error 해결 (#408)"

frontend/src/utils/constants.js
- 채점 결과 색상을 더 자연스럽고 부드러운 색상으로 변경하였습니다.
- 기존 색상
- 변경된 색상
N/A
N/A
=> #414 채점 결과 색상 개선

backend/submission/tests.py, backend/submission/views/oj.py
- 기존에 대회에 대한 제출은 조회가 아예 불가능했는데, 본인의 제출들은 조회할 수 있도록 수정하였습니다.
- `SubmissionListAPI`에서 `contest_id`를 쿼리 파라미터로 받을 수 있도록 수정하고, contest_id가 포함된 경우 자신의 제출에 대해서만 조회가 가능하도록 수정하였습니다.
- `contest_id`가 포함되지 않은 경우 기존의 로직을 유지하였습니다.
- Passes Unit Test
N/A
N/A
=> #413 본인의 대회 제출 기록 조회 기능 추가

deployment/docker-compose.dev.yml, deployment/docker-compose.hub.yml, deployment/docker-compose.prod.yml
- 새로운 개발 도메인에 맞추어서 image registry를 변경하였습니다.
N/A
N/A
N/A
=> #448 새로운 개발 도메인 Sync

frontend/deploy/swarm/web-frontend.yml
- `web-frontend.yml`에 개발 서버 주소를 변경하였습니다. `copl-dev.site` -> `code-place-dev.site`
N/A
N/A
N/A
=> #448 프론트엔드 web-frontend.yml 개발 서버 주소 변경
