- account/models.py
- account/serializers.py
- account/urls/oj.py
- account/views/oj.py
- oj/wsgi.py
- 일반 사용자의 랭킹 API를 추가하였습니다.
- 기존 API의 /acm-rank/user-rank 프론트 라우터를 /user-rank로 바꿔야할 것으로 보입니다.
- 오늘의 급상승 사용자 랭킹 API를 추가하였습니다.
- 학과별 랭킹 API를 추가하였습니다.
- 요청하신 학과 랭킹에 기여한 학생들의 정보도 같이 반환합니다. 
- 회원가입 시, UserProfile 모델의 School, Major 필드가 null로 되어있던 문제를 해결하였습니다.
> 랭킹 페이지 API 추가

- account/views/oj.py
- 학과 랭킹 API 응답의 avatar_url에 /public/avatar/ 디렉토리 경로가 중복되는 문제 해결
> 학과 랭킹 API 오류 수정

- backend/oj/settings.py
- 개발의 편리함을 위해 개발환경에서 CSRF를 허용합니다.
> chore: CSRF 미들웨어를 운영환경에서만 사용하도록 변경

- backend/banner/views/admin.py
주요 변경 사항
---
- 배너 순서 재조정 API가 실패 시, 에러 메시지만 반환하도록 수정
- 배너 순서 재조정 API에 유효하지 않는 요청에 대한 예외처리
- 배너 활성/비활성화 성공 시, 업데이트된 모든 배너데이터를 반환하도록 수정
> #166 refactor 어드민 배너 관리 api 수정

- backend/banner/views/admin.py
- backend/utils/api/api.py
- 모든 *APIView가 상속받고 있는 부모 클래스인 APIView 클래스에서 multipart-formdata를 처리할 때, 요청 body에 먼저 접근한 이후 formdata에 접근하는 로직이 있었습니다.
- 어떤 요청이 들어올 때, request.body에 직접 접근하여 이후 content-type에 따른 요청 처리 분기 시, 각각의 content 데이터에 정상적으로 접근이 안되고 있었습니다.
- multipart/formdata content-type 처리를 별도로 분리하여 우선적으로 처리하였습니다.
- request.body에 직접 접근하는 대신 request.POST와 request.FILES를 사용하여 스트림 소모 문제를 방지하고 여러 번 접근 가능한 데이터 구조를 만들었습니다.
> #174 bugfix 운영환경에서 multipart/formdata 전송 시 rawpostdataexception 오류 발생

- backend/contest/urls/oj.py
- 백엔드 내 대회 랭킹 API 엔드포인트가 기본 어드민 주소로 연결되어 있어, 엔드포인트 위치 수정
> fix: API 엔드 포인트 위치 변경

- frontend/src/i18n/oj/en-US.js
- frontend/src/pages/oj/views/contest/ContestList.vue
- frontend/src/pages/oj/views/contest/children/ACMContestRank.vue
- frontend/src/pages/oj/views/contest/children/ContestProblemList.vue
- frontend/src/pages/oj/views/contest/children/OIContestRank.vue
- frontend/src/store/modules/contest.js
- close #237 
- 문제 목록 페이지에 ACM 대회 타입 관련 도움말 추가
- 문제 목록 페이지에서 ACM 대회일 때, 총점 삭제
- 랭킹 페이지의 header 변경 (# -> 순위, 일반 사용자 목록 -> 대회 참가자)
- 랭킹 페이지의 api 받아와지지 않는 이슈 확인
- 개요 페이지의 종료 시간구하는 로직 확인
> #237 대회 상세 페이지 UI 변경

- frontend/src/pages/admin/views/problem/ProblemList.vue
- Resolve #318 
- 문제 리스트가 필요한 Route를 `PROBLEM_LIST_ROUTES`에 저장
- 문제 리스트가 필요한 Route에서만 `getProblemList()`를 호출하도록 변경
- `getProblemList()`가 Contest ID가 없어도 호출될 수 있도록 변경
- `problem-list`와 `contest-problem-list`에서 모두 작동할 수 있도록 수정
Local 환경에서 테스트
- `문제 목록`탭에서 문제 리스트 확인
- `대회 > 대회 목록 > 문제` 에서 문제 리스트 확인
- 다른 Admin 컴포넌트 정상 동작 확인
N/A
N/A
> #318 Admin페이지에서 문제 리스트 보이지 않는 현상 해결

- hub/css/welcome.css
- hub/welcome.html
- hub/welcome.js
- Extension 초기 세팅 시 레포지토리를 선택할 수 있는 `welcome.html`페이지 추가
- 레포지토리 선택 시 GitHub와 연동하는 script `welcome.js` 추가
- CSS 설정
N/A
N/A
> #331 Code Place Hub 레포지토리 연동 기능 추가

- hub/welcome.js
- 레포지토리가 연결되었을 때 파란색 체크 동그라미 추가
N/A
N/A
> #331 Code Place Hub 레포지토리 연결 페이지 디자인 개선

- hub/manifest.json
- `manifest.json` 파일 추가
- GitHub 인증 할 수 있도록 github.com에서 `util.js`, `github.js`, `authorize.js` 실행
N/A
N/A
N/A
> #337 manifest.json 파일 추가

- frontend/src/pages/oj/views/problem/problemSolving/problemSolvingComponent/ProblemDetailFlexibleContainer.vue
- 문제 페이지에 중요한 정보를 포함하고 있는 Elements에 고유한 ID를 부여
- 추가된 Elements: `title`, `difficulty`, `description`, input`, `output`, `limit`
- 파일 포맷팅 (현재 `Frontend` 디렉토리에 정규 Formatter가 구성이 안되어 있는 것 같음 - 추후 Fix 예정)
- ID를 가지고 Query Selector 실행
N/A
N/A
> #342 문제 페이지의 Elements에 고유 ID 추가

- hub/scripts/code-place/upload.js
- GitHub에 `README.md`에서 생성한 파일 GitHub Repository에 커밋 생성
- 로컬에서 문제 채점 후 테스트 레포지토리에 커밋되는지 확인
N/A
N/A
> #340 GitHub에 README.md 파일 업로드 구현

- hub/scripts/code-place/code_place.js
- hub/scripts/code-place/parse.js
- hub/scripts/code-place/variables.js
- Code Place 문제 페이지에 들어가면 Loader가 2초에 한번씩 Accepted되었는지 확인하는 로직 생성
- `window.location.href`와 `PROBLEM_URL_REGEX`를 비교해 문제 페이지인지 아닌지 확인
- ACCEPTED된 문제가 있으면 문제 정보 파싱 후 업로드 시작
- `CODE_PLACE_URL`과 같이 여러 스크립트에서 사용되는 상수 `variables.js`에 정의
- 문제 ACCEPT 후 테스트 레포지토리에 잘 커밋되는지 확인
N/A
N/A
> #340 Code Place Hub Loader 생성

- frontend/src/pages/oj/views/problem/problemSolving/problemSolvingComponent/CodeEditorHeader.vue
- hub/scripts/code-place/parse.js
- hub/scripts/code-place/upload.js
- hub/scripts/code-place/variables.js
- `CodeEditorHeader`에서 코드 언어를 가져올 수 있도록 `언어 선택`에 ID 추가 -> Code Place Hub는 이 ID를 통해 Query Selector로 언어를 가져옴
- Code Place Hub의 `upload()`함수에 code를 같이 push하도록 수정
- `variables.js`에 `선택된 언어 - 확장자` 매핑 변수 생성
- 로컬에서 문제 제출 후 정상적으로 업로드 되는지 확인
N/A
N/A
> #347 Code Place Hub 제출된 코드 커밋 구현

- hub/scripts/code-place/code_place.js
- Timer는 제출 상태가 10초동안 바뀌지 않을 경우 종료하기 위한 것인데, Loader와 Timer가 연동되어 있지 않아 제출이 성공해도 Timeout 되는 현상이 있었습니다. 이 PR은 timer와 loader를 함께 시작하고 함께 종료하여 항상 timeout 되는 문제를 해결합니다.
- 로컬 테스트
N/A
N/A
> #350 Code Place Hub의 Loader와 Timer 동기화

- hub/scripts/authorize.js
- hub/scripts/background.js
- hub/scripts/oauth2.js
- 기존: Chrome Extension에서 OAuth App Secret을 가지고 직접 Github에 Access Token을 발급
- 수정: Chrome Extension은 OAuth App Secret을 모름, 인증 서버에 임시 코드를 포함해 요청을 보내면 인증 서버가 Access Token을 발급
로컬 테스트
1. 인증 서버 실행
```
cd hub/auth_server
docker build -t hub_auth_server .
docker run -d -p 8081:80 --name hub_auth_server -e GITHUB_OAUTH_APP_ID=<비밀> -e GITHUB_OAUTH_APP_SECRET=<비밀> hub_auth_server
```
2. Chrome Extension에 로그 출력
N/A
N/A
> #362 Code Place Hub 인증 시 인증 서버를 통해 Access Token 발급

- hub/auth_server/app/main.py
- hub/auth_server/app/test_main.py
- 인증 서버에서 `github.com`에 대한 CORS 허용
- Chrome Extension이 Github에서 인증을 하고 인증 완료 후 Github 페이지에서 `authorize.js`에 의해 인증 서버로 API 요청을 보내므로 `github.com`에 대한 CORS 허용이 필요함
N/A
N/A
> #353 Code Place Hub 인증 서버 CORS 설정

- .github/workflows/ci2develop.yml
- .github/workflows/ci2production-and-release.yml
- deployment/docker-compose.hub.yml
- script/deploy-hub-stack.sh
- Code Place Hub 관련 릴리즈는 Code Place와 분리하였습니다.
- Code Place Hub 릴리즈는 `dev`, `prod` 로 나누지 않고 하나의 버전으로 통일하였습니다. 따라서 release 브랜치가 만들어 지는 경우에만 Code Place Hub 인증 서버 이미지가 업데이트됩니다.
- 추후 Code Place Hub의 Chrome Extension 배포가 시작되면 합쳐서 하나의 Code Place Hub 릴리즈 파이프라인을 구성할 예정입니다.
- 레지스트리에서 `code-place-dev`, `code-place-prod` 프로젝트와 분리된 `code-place-hub` 프로젝트로 이미지를 푸시하도록 하였습니다.
- 서버에서 Code Place Hub 인증 서버를 스택을 생성하는 스크립트 `deploy-hub-stack.sh`를 추가하였습니다.
1. 로컬에서 Docker Swarm으로 Code Place Hub 인증 서버 스택 deploy
```
docker swarm init
docker stack deploy -c docker-compose.hub.yml hub
```
2. dummy request를 보내고 요청 잘 들어오는지 확인
```
docker service logs hub_hub-auth
```
N/A
N/A
> #367 Code Place Hub 인증 서버 릴리즈 분리

- frontend/src/pages/oj/views/user/Register.vue
- 회원가입 시 부산대학교 웹메일이 없는 경우가 간혹 있어서, 쉽게 부산대학교 웹메일 회원가입을 진행할 수 있도록 description을 추가하였습니다.
- 파일 Formatting
N/A
N/A
> #355 회원가입 시 부산대학교 웹메일 관련 안내 추가

- hub/scripts/background.js
- Code Place Hub가 실행될 때 Chrome Context가 제대로 설정되지 않은 경우 Code Place Hub 메인 로직을 실행하지 않고 스킵하도록 수정하였습니다. 
- 적절한 Context를 설정하기 위해서는 새로고침이 필요한데, 새로고침을 강제로 구현하는 것은 UX 측면에서 단점이 될 것 같아 스킵하도록 설정하였습니다.
- 이 후, Context가 적절히 설정되지 않았을 때 유저에게 새로고침을 권유하는 로직을 구현할 예정입니다.
Code Place Hub를 설치하고 새로고침 않더라도 에러가 발생하지 않는 것 확인
N/A
N/A
> #378 Code Place Hub Context Error 수정

- frontend/src/pages/oj/views/contest/children/ContestProblemList.vue
- 대회 문제 탭의 Title에서 전체 문제 개수를 추가하였습니다.
N/A
N/A
> #385 대회 문제 탭에서 전체 문제 개수 표시

- backend/problem/tests.py
- backend/problem/urls/oj.py
- backend/problem/views/oj.py
- 스케줄러가 일주일에 한번씩 호출할 수 있는 `UpdateWeeklyStatsAPI` API View를 생성하였습니다.
- API 호출 시 모든 문제에 대해 `last_week_info`에 `curr_week_info`를 저장하고 `curr_week_info` 를 초기화하는 로직을 작성하였습니다.
- Problem 유닛테스트에서 커스텀 `display_id`를 가진 문제를 생성하기 위한 `create_problem_with_custom_display_id` staticmethod를 생성하였습니다.
- `UpdateWeeklyStatsAPI`를 테스트하는 코드를 작성하였습니다.
- 유닛테스트 커버리지 100%
N/A
N/A
> #394 문제 Weekly Stats 업데이트 API 생성

- backend/problem/tests.py
- backend/problem/urls/oj.py
- backend/problem/views/oj.py
- 보너스 문제를 Shuffle할 수 있는 API를 구현하였습니다.
- [VeryLow, Low] 에서 한 문제, [Mid]에서 한 문제, [High, VeryHigh]에서 한 문제를 뽑도록 하였습니다.
- Scheduler만 호출가능하도록 `scheduler_only` 데코레이터를 추가하였습니다.
- 유닛테스트를 작성하였습니다.
- 로컬에서 API 테스트 후 데이터베이스 확인 (완료)
- 유닛테스트 통과 (커버리지 100%)
N/A
N/A
> #394 보너스문제 셔플 API 구현

- backend/.gitignore
- backend/Dockerfile
- backend/account/tasks.py
- backend/account/tests.py
- backend/deploy/entrypoint.sh
- backend/deploy/requirements.txt
- backend/oj/celery.py
- backend/oj/settings.py
- backend/problem/tasks.py
- backend/problem/tests.py
- deployment/docker-compose.dev.yml
- deployment/docker-compose.prod.yml
- deployment/docker-compose.yml
- `Celery`를 비동기 작업 및 스케줄링 작업을 구현하였습니다.
- 아래의 기존 로직들을 담당합니다.
1. 사용자의 00시 기준 점수 업데이트
2. 사용자의 점수 변동 폭 업데이트 (현재 점수 - 기준 점수)
3. 한 주 동안의 문제 별 제출 현황, 성공률 업데이트
4. 한 주 동안의 보너스 문제 업데이트
- 스케줄링을 담당하는 `celery-beat`와 작업 처리를 담당하는 `celery-worker` 컨테이너를 스택에 추가하였습니다.
- Scheduler 컨테이너를 제거하였습니다.
- Beat
- Worker
- Unit Test Coverage
N/A
N/A
> #394 Celery 비동기 작업 큐 및 스케줄러 구현

- frontend/src/pages/oj/views/problem/problemSolving/Problem.vue
- frontend/src/pages/oj/views/problem/problemSolving/problemSolvingComponent/CodeHighlight.vue
- frontend/src/pages/oj/views/problem/problemSolving/problemSolvingComponent/SubmissionErrorDropdown.vue
- frontend/src/pages/oj/views/problem/problemSolving/problemSolvingComponent/SubmissionList.vue
- `CodeHighlight` 컴포넌트에 일반 텍스트를 표시하는 type인 `plaintext`를 추가하였습니다.
- `ErrorDropdown` 컴포넌트에 최초 테스트케이스의 입력값과 기대값 출력을 추가하였습니다.
- `CodeHighlight`를 사용할 때 max-width와 max-height를 설정하고, (overflow = scroll) 로 설정하였습니다.
- 최초 테스트케이스가 잘 나타나는지 확인
- 테스트케이스 정보가 없는 경우 (컴파일 에러 등 실행 전 오류) 테스트케이스를 표시하지 않는지 확인
N/A
N/A
> #413 최초 실패 테스트케이스 정보 조회 기능 추가

- backend/submission/tests.py
- backend/submission/urls/oj.py
- backend/submission/views/oj.py
- 특정 제출이 해당 문제의 모든 제출 중의 순위를 반환하는 API `SubmissionRankAPI`를 구현하였습니다.
- 해당 문제를 해결한 순위
- 시간 비용 순위 (언어별로 분리)
- 메모리 비용 순위 (언어별로 분리)
- `Submisison`에 실패하던 테스트들을 수정하여 통과하도록 수정하였습니다.
- 유닛테스트 결과
- API 테스트
N/A
N/A
> #413 제출 랭킹 API 구현

- frontend/src/pages/oj/views/problem/problemSolving/problemSolvingComponent/CodeHighlight.vue
- 기존에 Box Shadow가 라이트모드 기준으로 고정돼있어서 Dark/Light에 따라 Box Shadow를 동적으로 변경하도록 변경하였습니다.
- 라이트모드에서 호버 시 Shadow 확인
- 다크모드에서 호버 시 Shadow 확인
N/A
N/A
> #413 CodeHighlight 컴포넌트 스타일 개선

- frontend/src/pages/oj/views/problem/problemSolving/Problem.vue
- frontend/src/pages/oj/views/problem/problemSolving/problemSolvingComponent/SubmissionList.vue
- frontend/src/pages/oj/views/problem/problemSolving/problemSolvingComponent/SubmissionStatus.vue
- 문제 제출 후 결과가 나온 경우, 제출 현황 > 해당 제출 상세보기 드롭다운으로 이동시킵니다.
1. Problem 컴포넌트는 SubmissionList 컴포넌트에 `lastSubmisisonId`를 전달합니다.
2. 채점이 완료되면, lastSubmissionId를 해당 제출로 변경하고, SubmissionList 컴포넌트에 전달합니다.
3. SubmissionList 컴포넌트는 lastSubmissionId를 watch로 감시하고 있다가, 변경된 경우 제출 목록을 업데이트하고 해당 제출을 selectedSubmisison으로 설정합니다.
- 제출 현황에서 제출들이 드롭다운을 가지고 있는 것을 사용자들이 쉽게 알 수 있도록 각 행의 오른쪽에 화살표를 추가하였습니다.
- 제출 현황의 각 행들의 Padding을 늘렸습니다.
https://github.com/user-attachments/assets/d56979b8-ebe9-44d5-b397-c23e48b4008e
N/A
N/A
> #413 제출 현황 탭 UX 개선

- frontend/src/pages/admin/components/Simditor.vue
- Simditor의 언어 기본값이 중국어인데 이해하기 힘들어서 영어로 변경하였습니다. (아쉽게도 한국어는 지원하지 않습니다ㅜㅡㅜ)
- 문제 수정 탭에서 옵션이 영어로 표시되는지 확인
N/A
N/A
> #439 Simditor 언어 영어로 변환

- deployment/docker-compose.monitoring.yml
- deployment/prometheus.yml
- 모니터링 전용 Docker network인 `monitoring`을 생성하였습니다.
- 컨테이너의 메트릭을 수집하고 시각화하기 위한 모니터링 Docker Stack을 구성하였습니다.
- `cadvisor`: **Docker 컨테이너의 메트릭을 수집**하여 Prometheus가 가져갈 수 있도록 노출하는 에이전트입니다.
- version: 0.52.0
- port: 8080
- `prometheus`: cadvisor가 수집한 메트릭을 수집하여 **시계열 데이터로 저장**합니다.
- version: 3.5.0
- port: 9090
- `grafana`: prometheus가 수집한 메트릭을 **시각화**합니다.
- version: 11.6.3
- port: 3000
- Docker Stack 생성 결과
- `cadvisor`
- `prometheus`
- `grafana`
N/A
N/A
> #444 모니터링 Docker Stack 생성

- deployment/docker-compose.monitoring.yml
- 모니터링은 `cadvisor` -> `prometheus` -> `grafana`로 구성되어 있습니다. 하지만 `grafana`이외에 다른 서비스는 외부에서 접근할 필요가 없는 서비스들이므로 포트 매핑을 제거하였습니다.
모니터링 기능 정상 작동 여부 확인
N/A
N/A
> #446 불필요한 포트 매핑 제거

- backend/submission/models.py
디버깅 결과 아래와 같은 오류가 백엔드 서버에 출력되고 있었습니다.
```
AttributeError: 'Submission' object has no attribute 'user_avatar'
```
확인 결과, #454 에서 실수로 `user_avatar` property를 삭제하여 생긴 오류였습니다. (제 불찰입니다 ㅜㅡㅜ)
- `Submission` 모델에 `user_avatar` property를 추가하였습니다.
N/A
N/A
> #455 내 제출현황이 표시되지 않는 오류 수정

- deployment/docker-compose.dev.yml
- deployment/docker-compose.prod.yml
- 채점 서버 버전을 1.0.0-beta -> 1.0.1 로 변경하였습니다.
- 1.0.1 버전은 비정상적인 시간 측정을 해결하는 변경사항을 포함하고 있습니다.
- 관련 PR: https://github.com/pnu-code-place/JudgeServer/pull/2
- Production 스택에서 안정적인 채점을 위해 `vCPU=1.00`, `memory=1GB` 로 고정하였습니다.
N/A
N/A
N/A
> #457 채점 서버 버전 1.0.1로 변경

- backend/contest/serializers.py
#464 를 급하게 머지하는 과정에서 PUT 요청에 대해서도 처리하는 걸 깜빡했습니다..
- `EditContestSerializer`에 `allow_paste`를 추가하여 클라이언트에서 전달되는 `allow_paste`값은 정상적으로 받을 수 있도록 변경하였습니다.
- 로컬에서 변경 사항이 잘 적용되는지 여부 테스트
https://github.com/user-attachments/assets/e7611360-139b-4db2-a176-b96d7c79479f
N/A
N/A
> #463 대회 정보 변경 시 붙여넣기 허용 여부가 변경되지 않는 오류 수정

- backend/.gitignore
- backend/init_db.sh
로컬에서 테스트하다가 데이터를 날리게 되면 생각보다 꽤 번거롭고 화가 납니다...ㅎ_ㅎ
따라서 로컬에서도 실수로 컨테이너를 삭제했을 때 데이터를 잃지 않도록 바인딩을 추가했습니다.
- `init_db.sh`에 postgres, redis에 대한 디렉토리 바인딩을 추가했습니다.
- postgres: `backend/data/postgres`
- redis: `backend/data/redis`
- `init_db.sh` 실행 후 `backend/data/` 디렉토리에서 바인딩 여부 확인
N/A
N/A
> #NOISSUE 로컬 환경에서 데이터베이스 생성 시 디렉토리 바인딩
